### ISSUE TITLE
Statment

### ISSUE THREAD

**Issue by Just-xx** [IREK-szef/games-blocklist#1]
## Oświadczenie
Uważam, że repozytorium jest niestosowne w świetle naszego prawa. Mianowicie zasoby tego repozytorium ograniczają dostęp do powszechnego internetu dla użytkowników naszej szkoły (CKZiU w Strzelcach Krajeńskich), co w rezultacie niesie za sobą nieposzanowanie podstawowych praw obywatelskich zawartych w konstytucji.

## Wniosek
Wnioskuje o całkowite usunięcie repozytorium oraz niestosowanie jego plików w celu blokowania zasobów internetowych w placówce.
Jeśli ten wniosek nie przyniesie skutków, nasz samorząd klasowy będzie zmuszony do podjęcia radykalnych środków.

*Pozdrawiam*
*Jakub D.*

**Comment by IREK-szef** [comment]
Przykro mi, ale wniosek muszę oddalić. Zapewniam że lista w żaden sposób nie narusza konstytucji Rzeczpospolitej Polskiej. A prawo oświatowe nie zabrania administratorom, a nawet nakłada obowiązek korzystanie z takich list:

> **Art. 27. Prawo oświatowe**
> _Działania zabezpieczające dostęp uczniów do niektórych treści_
> Szkoły i placówki zapewniające uczniom dostęp do Internetu są obowiązane podejmować działania zabezpieczające uczniów przed dostępem do treści, które mogą stanowić zagrożenie dla ich prawidłowego rozwoju, w szczególności zainstalować i aktualizować oprogramowanie zabezpieczające.

Pozdrawiam
IREK-szef
